version: '3.7'
services:
    nginx:
        image: nginx:1.21-alpine
        ports:
            - "50080:80"
        restart: unless-stopped
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        image: tongwoo/php:7.4.22
        working_dir: /app
        restart: unless-stopped
        command: /bin/bash -c "/opt/remi/php74/root/bin/php composer.phar install -v && /opt/remi/php74/root/sbin/php-fpm"
        privileged: true
        volumes:
            - .:/app
            - ./docker/php/custom.ini:/etc/opt/remi/php74/php.d/custom.ini
            - ./docker/php/error.log:/var/opt/remi/php74/log/php-fpm/error.log
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "53306:3306"
        restart: unless-stopped
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        volumes:
            - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./docker/mysql/data:/var/lib/mysql
